plugins {
    id 'com.android.application'
}

android {
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId "io.github.abdurazaaqmohammed.gamesbox"
        minSdk 1
        targetSdk 37
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'io.github.abdurazaaqmohammed.gamesbox'

    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}

dependencies {
}
